#!/usr/bin/env perl

use strict;

###############################################################################
sub showColor {
    my @fgbg = qw{38 48};
    my @colors = (1...256);

    foreach my $g (@fgbg) {
        foreach my $color (@colors) {
            printf "\033[%d;5;%dm %3d\033[0m", $g, $color, $color;
            print "\n" if $color%16==0;
        }
    }
}
###############################################################################
sub usage {
    print "usage: color256 fg bg msg\n";
    print "eg: color256 10 27 \"this is a test string\"\n";
}
###############################################################################
if ($#ARGV == -1) { showColor() ; exit; }
if ($#ARGV !=  2) {      usage(); exit; }

my $fg  = $ARGV[0];
my $bg  = $ARGV[1];
my $msg = $ARGV[2];

print "fg=$fg, bg=$bg\n";
print "\033[38;5;".$fg."m\033[48;5;".$bg."m".$msg."\033[0m\n";
